using { USERS } from '../db/Schema';

entity VERUSER as select 
    key ID,
        CEDULA,
        NOMBRE,
        DIRECCION,
        MUNICIPIO,
        EMAIL,
        FECHA_NACIMIENTO,
        CELULAR,
        ESTADO,
        INICONTRATO,
        FINCONTRATO,
        createdAt,
        TO_INTEGER(MONTHS_BETWEEN(TO_DATE(INICONTRATO, 'YYYY-MM-DD'), (CASE WHEN FINCONTRATO IS NULL THEN CURRENT_DATE ELSE FINCONTRATO END) ) / 12) AS ANTIGUEDADA: Integer,
        MOD(MONTHS_BETWEEN(TO_DATE(INICONTRATO, 'YYYY-MM-DD'), (CASE WHEN FINCONTRATO IS NULL THEN CURRENT_DATE ELSE FINCONTRATO END) ), 12) AS ANTIGUEDADM: Integer,
        TO_INTEGER(MONTHS_BETWEEN(TO_DATE(FECHA_NACIMIENTO, 'YYYY-MM-DD'), CURRENT_DATE) / 12) AS EDAD : Integer
        from USERS;

        //Falta mostrar creado por y cuando
